version: '2'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/home/app/web
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    restart: always  
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgis
    restart: always  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_db
  nginx:
    build: ./nginx
    restart: always  
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: