version: '2'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web
    ports:
      - "8000:8000"
    restart: always  
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgis/postgis
    restart: always  
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_db

volumes:
  postgres_data: