# Generated by Django 4.1.1 on 2022-09-08 06:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorldBorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("area", models.IntegerField(verbose_name="Area")),
                ("pop2005", models.IntegerField(verbose_name="Population 2005")),
                ("fips", models.CharField(max_length=2, verbose_name="FIPS Code")),
                ("iso2", models.CharField(max_length=2, verbose_name="2 Digit ISO")),
                ("iso3", models.CharField(max_length=3, verbose_name="3 Digit ISO")),
                ("un", models.IntegerField(verbose_name="United Nations Code")),
                ("region", models.IntegerField(verbose_name="Region Code")),
                ("subregion", models.IntegerField(verbose_name="Sub-Region Code")),
                ("lon", models.FloatField(verbose_name="Lon")),
                ("lat", models.FloatField(verbose_name="Lat")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        srid=4326, verbose_name="Mpoly"
                    ),
                ),
            ],
        ),
    ]
